apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
  namespace: test-hello-app
data:
  index.html: |
    <html>
    <head><title>Hello World</title></head>
    <body>
      <h1>Hello World!</h1>
    </body>
    </html>

