kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30007   
  type: NodePort
